In [1]:
import numpy as np

In [3]:
myMatrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
myMatrix = np.zeros([4,4],dtype=np.int32)
myMatrix

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [10]:
# tipo de matrix:
myMatrix = np.asmatrix([[1,2,3],[4,5,6],[7,8,9]])
myMatrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# muda o tamanho de uma matrix
myMatrix.reshape((1,9))

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [22]:
myMatrix.transpose()

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [23]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Exemplo de balanceamento que ocorre com as matrizes
inputs = np.array([5,10,15])
weights = np.array([[.5,.2,-1], [.3,.4,.1],[-.2,.1,.3]])

result = np.dot(inputs,weights)
print(result)

[2.5 6.5 0.5]


In [27]:
def doAdd(a,b):
    return a + b

vectAdd = np.vectorize(doAdd)

print(vectAdd([1,2,3,4],[1,2,3,4]))

[2 4 6 8]
